### ISSUE TITLE
[PATCH]: Solve Alignment and Layout Issues

### ISSUE THREAD

**Issue by AbhijithGanesh** [dscvitc/dscvitchennai#36] opened 2022-10-08 18:51 UTC
# Layout Issue
<tr/>

Currently, the Layout isn't aligned correctly and the movement is incorrect vis-a-vis responsiveness. I would like to work on patching the issue!

**Comment by AbhijithGanesh** [comment] 2022-10-08 18:51
![image](https://user-images.githubusercontent.com/67182544/194723059-79e66837-59ae-4302-8ba0-cc93e6df7408.png)

**Comment by jessej-samuel** [comment] 2022-10-08 21:12
Hey, this issue is a duplicate of #10 & #11 both of which were already assigned 👀

**Comment by AbhijithGanesh** [comment] 2022-10-09 04:13
No #10 is about being responsive right, my PR isn't responsive, it only works for large screens, so it isn't a duplicate of another

**Comment by AbhijithGanesh** [comment] 2022-10-09 04:19
Already patched to dev branch. Duplicate PR

**Closed** 2022-10-09 04:19 UTC
