### ISSUE TITLE
NavBar buttons aren't working

### ISSUE THREAD

**Issue by AnshuPathak-88825** [dscvitc/dscvitchennai#82] opened 2022-10-28 17:54 UTC
### Description

there's no any link avaible in navbar button

### What happened?

A bug happened! when we click button that will take us  to that section

### Version

Don't know version

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhijithGanesh** [comment] 2023-01-11 05:50
@Arjun31415 I would like to be assigned to this

**Comment by AbhijithGanesh** [comment] 2023-01-11 05:51
Duplicate of #81

**Closed** 2023-01-11 14:41 UTC
Labels: bug
